apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-o0o8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-o0o8
    app.kubernetes.io/part-of: tkrw-pr712-0075-0036-app
  name: devfile-sample-o0o8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-o0o8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-o0o8
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-o0o8@sha256:59c017f09f4c3085376c0d249cb07e8b48482ef06c4c40ae30a1caa728fde85e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
